version: '3.8'

services:
  backend.api:
    image: backend-api
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backendapi-network
    depends_on:
      - backend.database

  backend.database:
    container_name: "backend.database"
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backendapi-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      - VITE_BACKEND_URL=http://backend.api:8080
    depends_on:
      - backend.api

volumes:
  postgres_data:
    driver: local

networks:
  backendapi-network:
    driver: bridge
